spring:
  cache:
    redis:
      time-to-live: 30000
  datasource:
    url: jdbc:h2:mem:proddb
    username: prod
    password: 1234
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
      format_sql: true
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations:
        - classpath:data-prod.sql